### ISSUE TITLE
Implement closing tab variation

### ISSUE THREAD

**Issue by victorporof** [victorporof/tofino#27]
Mockup with web contents animation: https://mozilla.slack.com/files/epang/F4YB8EPS4/close_tab_3_-_variation.mp4

Mockup without: https://drive.google.com/file/d/0B9o41Fwl8FagOU1tdXQzbVNUdXM/view

**Comment by victorporof** [comment]
@ericawright did you want to check this out?

**Comment by ericawright** [comment]
Yes. Have also been spending a bit of time on this. Nothing to show for it yet. It is related to the opening animation for connected tabs https://drive.google.com/file/d/0B9o41Fwl8FagMUo1SkN5MFhFcEU/view
