### ISSUE TITLE
Implement loading tab animations

### ISSUE THREAD

**Issue by victorporof** [victorporof/tofino#28]
Spec: https://drive.google.com/file/d/0B9o41Fwl8FagYTdIQ29IVHNQUUE/view

**Comment by victorporof** [comment]
@ericawright did you want to check this out?

We could split work between this and #27, or feel free to take them both if you want to explore this.

**Comment by ericawright** [comment]
Yes, I have a branch that has some of it already.  https://github.com/ericawright/tofino/tree/spinners
Today is a holiday in Canada, so I'll be working on it on Monday
